services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: indy-scca-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
